apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::1111111111:role/service-role/s3-access-role"
spec:
  serviceAccountName: "s3-access-sa"
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80